# Generated by Django 3.1.5 on 2022-10-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=40)),
                ('member_id', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=40, unique=True)),
                ('overdue', models.IntegerField(default=0)),
                ('type_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
