# Generated by Django 3.1.5 on 2022-10-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('postname', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_id', to='account.user')),
                ('p_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.posttype')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_content', models.TextField()),
                ('member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_id', to='account.user')),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
        ),
    ]
